CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_PMW3610=y
CONFIG_PMW3610_CPI=400
CONFIG_PMW3610_ORIENTATION_270=y
CONFIG_PMW3610_SNIPE_CPI=400
CONFIG_ZMK_POINTING_POLL_RATE=100
CONFIG_PMW3610_INVERT_X=y
CONFIG_PMW3610_SMART_ALGORITHM=n
